import { Navbar } from "@/components/navbar";
import { cn } from "@protest/shared";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex min-h-screen flex-col px-4 md:px-10 md:py-8 gap-8 container mx-auto"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
